cont:
  - heading: "Best Practices"
    text: "Shows you best practices in cloud implementations that are relevant to you."
    icon: "/assets/icons/01.svg"
  - heading: "Cost Savings"
    text: "Identify specific savings and benefits the cloud will bring to your business."
    icon: "/assets/icons/02.svg"
  - heading: "Cloud Ready Candidates"
    text: "Identify services and applications that can cost-effectively move to the cloud to reduce the On-Premise software burden on your infrastructure."
    icon: "/assets/icons/03.svg"
  - heading: "Risk Factors"
    text: "We’ll indicate the risks and what can be done to minimize them, and address concerns surrounding security, scalability and accessibility.<br>
    Implementation Strategy: Outlines a custom implementation roadmap and impact on your legacy applications."
    icon: "/assets/icons/04.svg"
  - heading: "Monitoring"
    text: "We offer full-stack monitoring services that helps organizations manage and optimize the applications and other IT infrastructure hosted on the cloud."
    icon: "/assets/icons/05.svg"
  - heading: "Seamless integration"
    text: "Seamless integration – we can provide both ‘Cloud to Cloud’ and ‘Cloud to Ground’ integration, to both new and legacy systems. Our effective back-end integration provides you with a single, real-time view of your customers and products. We can also manage the successful migration of your data."
    icon: "/assets/icons/06.svg"
  - heading: "Cloud security"
    text: "Cloud security duties including design, planning, management, maintenance and support. Identify and work through cloud security issues such as authentication, APIs, system vulnerabilities, web services, DoS attacks, and multi-tenant risk."
    icon: "/assets/icons/07.svg"
  - heading: "Training"
    text: "Microservices, Cloud native applications, Containers, Kubernetes are what most organizations are thinking about these days. Cloud Native Computing Foundation is assembling projects that help with building cloud native applications. We can give training on kubernetes, aws or most of the cloud solutions."
    icon: "/assets/icons/08.svg"
